In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Etudes\projects\data drills maven\Readmission Radar\inpatient_admissions.csv",
                 parse_dates=['admission_date', 'discharge_date'])
df.head()

  admission_id patient_id admission_date discharge_date
0     ADM00001      P0092     2015-01-07     2015-01-08
1     ADM00002      P0070     2015-01-18     2015-01-19
2     ADM00003      P0127     2015-01-19     2015-01-20
3     ADM00004      P0003     2015-01-23     2015-01-24
4     ADM00005      P0085     2015-01-23     2015-01-24

In [4]:
df["readmission_date"] = (
    df.sort_values(by="admission_date")
    .groupby("patient_id")["admission_date"]
    .shift(-1)
)
df["duration"] = (df["readmission_date"] - df["discharge_date"]).dt.days
df.head()

,admission_id,patient_id,admission_date,discharge_date,readmission_date,duration
0,ADM00001,P0092,2015-01-07,2015-01-08,2015-02-06,29.0
1,ADM00002,P0070,2015-01-18,2015-01-19,2015-02-17,29.0
2,ADM00003,P0127,2015-01-19,2015-01-20,2016-11-16,666.0
3,ADM00004,P0003,2015-01-23,2015-01-24,NaT,NaN
4,ADM00005,P0085,2015-01-23,2015-01-24,2015-02-13,20.0

In [5]:
from numpy import where
df["readmitted_in_30_days"] = where(df["duration"] <= 30, 1, 0)
df.head()

,admission_id,patient_id,admission_date,discharge_date,readmission_date,duration,readmitted_in_30_days
0,ADM00001,P0092,2015-01-07,2015-01-08,2015-02-06,29.0,1
1,ADM00002,P0070,2015-01-18,2015-01-19,2015-02-17,29.0,1
2,ADM00003,P0127,2015-01-19,2015-01-20,2016-11-16,666.0,0
3,ADM00004,P0003,2015-01-23,2015-01-24,NaT,NaN,0
4,ADM00005,P0085,2015-01-23,2015-01-24,2015-02-13,20.0,1

In [6]:
readmission_rate = df.loc[:, "readmitted_in_30_days"].sum() / len(df)
print(f"Readmission rate: {readmission_rate}")

Readmission rate: 0.3723916532905297