In [2]:
import pandas as pd
import numpy as np
df_orders = pd.read_csv(r"C:\Etudes\projects\data drills maven\Spot The Sale\orders.csv", parse_dates=["order_date"])
df_promotions = pd.read_csv(r"C:\Etudes\projects\data drills maven\Spot The Sale\promotions.csv", parse_dates=["start_date", "end_date"])
df_promotions.head(30)

  promo_id        promo_name start_date   end_date
0  BF_2023      Black Friday 2023-11-24 2023-11-29
1  NY_2024     New Year Sale 2024-01-01 2024-01-07
2  SB_2024    Summer Blowout 2024-07-15 2024-07-31
3  BF_2024      Black Friday 2024-11-25 2024-11-30
4  NY_2025     New Year Sale 2025-01-01 2025-01-07
5  SC_2025  Spring Clearance 2025-03-10 2025-03-20

In [3]:
merged = pd.merge_asof(
    df_orders.sort_values("order_date").reset_index(drop=True),
    df_promotions.sort_values("start_date").reset_index(drop=True),
    left_on="order_date",
    right_on="start_date",
    direction="backward"
)
merged = merged.query("order_date <= end_date")
merged

,order_id,order_date,order_quantity,promo_id,promo_name,start_date,end_date
609,610,2023-11-24,2,BF_2023,Black Friday,2023-11-24,2023-11-29
610,612,2023-11-25,3,BF_2023,Black Friday,2023-11-24,2023-11-29
611,611,2023-11-25,5,BF_2023,Black Friday,2023-11-24,2023-11-29
612,613,2023-11-27,1,BF_2023,Black Friday,2023-11-24,2023-11-29
613,614,2023-11-28,2,BF_2023,Black Friday,2023-11-24,2023-11-29
...,...,...,...,...,...,...,...
1947,1952,2025-03-20,2,SC_2025,Spring Clearance,2025-03-10,2025-03-20
1948,1951,2025-03-20,1,SC_2025,Spring Clearance,2025-03-10,2025-03-20
1949,1948,2025-03-20,3,SC_2025,Spring Clearance,2025-03-10,2025-03-20
1950,1949,2025-03-20,2,SC_2025,Spring Clearance,2025-03-10,2025-03-20
1951,1950,2025-03-20,4,SC_2025,Spring Clearance,2025-03-10,2025-03-20

In [4]:
print(len(merged))

149