In [1]:
import pandas as pd
df_users = pd.read_csv(r"C:\Etudes\projects\data drills maven\Time Shift\users.csv")
df_tickets = pd.read_csv(r"C:\Etudes\projects\data drills maven\Time Shift\tickets.csv")
df_tickets["submitted_at_utc"] = pd.to_datetime(df_tickets["submitted_at_utc"].str.replace("T", " "))
df_users.head()

   user_id      country                              timezone
0        1   Bangladesh                    GMT +06:00 — Dhaka
1        2      Iceland      GMT +00:00 — Monrovia, Reykjavik
2        3  South Korea                    GMT +09:00 — Seoul
3        4        Japan    GMT +09:00 — Osaka, Sapporo, Tokyo
4        5     Thailand  GMT +07:00 — Bangkok, Hanoi, Jakarta

In [3]:
df_users["timezone"] = df_users["timezone"].apply(lambda x: str(x)[4:7]).astype("int32")
df_users.head()

   user_id      country  timezone
0        1   Bangladesh         6
1        2      Iceland         0
2        3  South Korea         9
3        4        Japan         9
4        5     Thailand         7

In [4]:
df_tickets = df_tickets.merge(df_users, on="user_id", how="left")
df_tickets.head()

   ticket_id  user_id    submitted_at_utc       country  timezone
0          1      546 2026-03-03 05:16:33      Pakistan         5
1          2      359 2026-03-06 12:26:33         Ghana         0
2          3      655 2026-03-02 08:05:55  Saudi Arabia         3
3          4      304 2026-04-02 04:33:34         Kenya         3
4          5       98 2026-04-03 01:54:55      Pakistan         5

In [6]:
df_tickets["local_time"] = df_tickets["submitted_at_utc"] + pd.to_timedelta(df_tickets["timezone"], unit="h")
df_tickets.head()

,ticket_id,user_id,submitted_at_utc,country,timezone,local_time
0,1,546,2026-03-03 05:16:33,Pakistan,5,2026-03-03 10:16:33
1,2,359,2026-03-06 12:26:33,Ghana,0,2026-03-06 12:26:33
2,3,655,2026-03-02 08:05:55,Saudi Arabia,3,2026-03-02 11:05:55
3,4,304,2026-04-02 04:33:34,Kenya,3,2026-04-02 07:33:34
4,5,98,2026-04-03 01:54:55,Pakistan,5,2026-04-03 06:54:55

In [7]:
df_hourly =(
    df_tickets
    .groupby(df_tickets["local_time"].dt.hour)
    .agg(count_tickets = ("ticket_id", "count"))
)
df_hourly.sort_values(by="count_tickets", ascending=False, inplace=True)
df_hourly

            count_tickets
local_time
10                   3985
9                    3587
11                   3572
12                   2607
8                    2594
13                   1606
7                    1587
6                     782
14                    749
15                    328
5                     326
16                    114
4                      97
3                      27
17                     22
2                      10
18                      3
1                       1
19                      1
20                      1
21                      1