In [1]:
from shlex import split

import pandas as pd
df = pd.read_csv(r"C:\Etudes\projects\data drills maven\2025 MLB positions\baseball_positions.csv")
df.head(20)

                  Name Team Position
0          Aaron Judge  NYY    OF/DH
1          Cal Raleigh  SEA     C/DH
2        Shohei Ohtani  LAD       DH
3            Juan Soto  NYM       OF
4         Tarik Skubal  DET       SP
5      Garrett Crochet  BOS       SP
6       Kyle Schwarber  PHI       DH
7         José Ramírez  CLE    3B/DH
8          Paul Skenes  PIT       SP
9       Bobby Witt Jr.  KCR       SS
10     George Springer  TOR    OF/DH
11    Francisco Lindor  NYM       SS
12     Julio Rodríguez  SEA       OF
13           Bryan Woo  SEA       SP
14     Geraldo Perdomo  ARI       SS
15      Corbin Carroll  ARI       OF
16     Junior Caminero  TBR       3B
17        Hunter Brown  HOU       SP
18  Cristopher Sánchez  PHI       SP
19      Freddy Peralta  MIL       SP

In [2]:
positions = []
for i in df["Position"]:
    positions += i.split("/")

{'2B': 125, 'C': 106, 'SP': 227, 'DH': 134, '3B': 127, '1B': 114, 'SS': 85, 'OF': 294, 'RP': 222}

In [4]:
df_positions = pd.DataFrame.from_dict(
    {"Position": positions}
)
df_positions

     Position
0          OF
1          DH
2           C
3          DH
4          DH
...       ...
1429       OF
1430       DH
1431       SP
1432       SP
1433       SP

[1434 rows x 1 columns]

In [7]:
df_positions = (
    df_positions
    .groupby("Position")
    .agg({"Position": "count"})
)
df_positions.columns = ["Count"]
df_positions.sort_values(by="Count", ascending=False, inplace=True)
df_positions

          Count
Position
OF          294
SP          227
RP          222
DH          134
3B          127
2B          125
1B          114
C           106
SS           85