In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Etudes\projects\data drills maven\Final Form\employee_satisfaction_survey.csv", parse_dates=["Timestamp"])
df.head(10)

            Timestamp                   Email  Satisfaction
0 2019-01-09 11:16:03  jack_torrence@acme.com             5
1 2019-01-14 17:03:20        talagbe@acme.com             5
2 2019-06-30 12:27:22       kennetht@acme.com             4
3 2019-09-09 12:30:08        cybarra@acme.com             2
4 2019-11-01 09:33:33      mia_brown@acme.com             4
5 2019-11-06 10:03:07          bradp@acme.com             1
6 2020-01-06 14:56:41  vito_corleone@acme.com             5
7 2020-01-06 15:23:21  afoster-baker@acme.com             3
8 2020-01-07 14:11:45         nsadki@acme.com             5
9 2020-01-12 12:56:55         kissys@acme.com             2

In [6]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])
df_last = (
    df.sort_values(by="Timestamp")
    .groupby("Email")
    .agg({"Satisfaction": "last"})
)
df_last.head(10)

                           Satisfaction
Email
adelarge@acme.com                     4
adells@acme.com                       3
adils@acme.com                        4
aforrest@acme.com                     3
afoster-baker@acme.com                1
aheitzman@acme.com                    2
ahitchcock@acme.com                   4
alain_robinson@acme.com               5
alejandro_bacong@acme.com             4
alexandrak@acme.com                   5

In [7]:
df_count = (
    df_last.groupby("Satisfaction")
    .agg(Employees = ("Satisfaction", "count"))
)
df_count.sort_values(by="Satisfaction", ascending=False)
df_count

              Employees
Satisfaction
1                    19
2                    34
3                    52
4                    83
5                    89