In [1]:
import pandas as pd
df_users = pd.read_csv(r"C:\Etudes\projects\data drills maven\Movie Metrics\Users.csv")
df_acts = pd.read_csv(r"C:\Etudes\projects\data drills maven\Movie Metrics\activity.csv", parse_dates=["date"])
df_acts.head()

   id  user_id       date                movie_name  finished
0   1        2 2023-06-22  The Shawshank Redemption         1
1   2        1 2023-07-23                     Shrek         0
2   3        4 2023-07-27                Fight Club         1
3   4        1 2023-08-23         Top Gun: Maverick         0
4   5        4 2023-08-24               Oppenheimer         0

In [2]:
df_fin = df_acts[df_acts["finished"] == 1]
df_fin.head(10)

    id  user_id       date                movie_name  finished
0    1        2 2023-06-22  The Shawshank Redemption         1
2    3        4 2023-07-27                Fight Club         1
5    6        4 2023-08-27                The Matrix         1
6    7        5 2023-09-07         Top Gun: Maverick         1
7    8        4 2023-09-10  The Shawshank Redemption         1
8    9        1 2023-09-12               Turning Red         1
9   10        1 2023-09-14   Spider-Man: No Way Home         1
10  11        5 2023-09-25                    Frozen         1
11  12        5 2023-09-25                      Nope         1
12  13        5 2023-09-30               Oppenheimer         1

In [3]:
df_started = df_acts.groupby(by = "user_id").agg({"id": "count"})
df_started.rename(columns= {"id": "started"}, inplace = True)
df_started

         started
user_id
1             30
2             15
3             10
4             43
5             31
6             13
7              2
8             29
9             17
10             7
11             2
12            46
13             5
14            14
15            20
16            29
17            23
18            35
19            20
20            34
21            35
22            36
23            24
24            17
25            23

In [4]:
df_metrics = (
    df_fin
    .sort_values(by = ["user_id", "date", "id"])
    .groupby(by= "user_id")
    .agg(
        {"user_id": "count",
         "date": ["min", "max"],
         "movie_name": ["first", "last"],})
)
df_metrics.columns = ["finished", "first_date", "last_date", "first_movie", "last_movie"]
df_metrics

,finished,first_date,last_date,first_movie,last_movie
user_id,,,,,
1,26,2023-09-12,2025-03-26,Turning Red,Her
2,12,2023-06-22,2025-05-01,The Shawshank Redemption,Fight Club
3,7,2023-11-10,2025-03-31,Oppenheimer,Nope
4,34,2023-07-27,2025-05-09,Fight Club,Avengers: Endgame
5,25,2023-09-07,2025-03-14,Top Gun: Maverick,Bohemian Rhapsody
6,11,2023-12-18,2025-03-27,Inception,The Revenant
7,2,2024-08-28,2024-09-15,Avengers: Endgame,Soul
8,23,2024-01-24,2025-04-25,Arrival,Whiplash
9,12,2024-02-25,2025-04-11,Big Hero 6,Moonlight
10,6,2024-05-01,2025-03-08,Whiplash,Knives Out
11,1,2025-01-29,2025-01-29,Avengers: Endgame,Avengers: Endgame
12,38,2024-04-11,2025-05-08,Get Out,Inside Out
13,5,2024-09-19,2025-05-16,Bohemian Rhapsody,Soul
14,12,2024-09-29,2025-05-10,Spider-Man: No Way Home,Parasite
15,14,2024-09-21,2025-05-05,Dune,Forrest Gump
16,21,2024-10-12,2025-04-30,Everything Everywhere All At Once,Parasite
17,19,2024-09-01,2025-05-11,Forrest Gump,Shrek
18,28,2024-10-01,2025-05-16,Fight Club,Fight Club
19,14,2024-12-21,2025-05-14,The Social Network,Coco
20,19,2024-11-27,2025-05-02,Luca,Fight Club
21,29,2025-01-03,2025-05-14,Up,Forrest Gump
22,28,2025-01-14,2025-05-13,Knives Out,Big Hero 6
23,17,2025-01-31,2025-05-04,Gladiator,Mad Max: Fury Road
24,17,2025-02-05,2025-05-16,Dune,The Social Network
25,17,2025-04-07,2025-05-10,Spider-Man: No Way Home,Bohemian Rhapsody

In [5]:
df_metrics = df_started.merge(df_metrics, on = "user_id", how = "inner")
df_metrics

,started,finished,first_date,last_date,first_movie,last_movie
user_id,,,,,,
1,30,26,2023-09-12,2025-03-26,Turning Red,Her
2,15,12,2023-06-22,2025-05-01,The Shawshank Redemption,Fight Club
3,10,7,2023-11-10,2025-03-31,Oppenheimer,Nope
4,43,34,2023-07-27,2025-05-09,Fight Club,Avengers: Endgame
5,31,25,2023-09-07,2025-03-14,Top Gun: Maverick,Bohemian Rhapsody
6,13,11,2023-12-18,2025-03-27,Inception,The Revenant
7,2,2,2024-08-28,2024-09-15,Avengers: Endgame,Soul
8,29,23,2024-01-24,2025-04-25,Arrival,Whiplash
9,17,12,2024-02-25,2025-04-11,Big Hero 6,Moonlight
10,7,6,2024-05-01,2025-03-08,Whiplash,Knives Out
11,2,1,2025-01-29,2025-01-29,Avengers: Endgame,Avengers: Endgame
12,46,38,2024-04-11,2025-05-08,Get Out,Inside Out
13,5,5,2024-09-19,2025-05-16,Bohemian Rhapsody,Soul
14,14,12,2024-09-29,2025-05-10,Spider-Man: No Way Home,Parasite
15,20,14,2024-09-21,2025-05-05,Dune,Forrest Gump
16,29,21,2024-10-12,2025-04-30,Everything Everywhere All At Once,Parasite
17,23,19,2024-09-01,2025-05-11,Forrest Gump,Shrek
18,35,28,2024-10-01,2025-05-16,Fight Club,Fight Club
19,20,14,2024-12-21,2025-05-14,The Social Network,Coco
20,34,19,2024-11-27,2025-05-02,Luca,Fight Club
21,35,29,2025-01-03,2025-05-14,Up,Forrest Gump
22,36,28,2025-01-14,2025-05-13,Knives Out,Big Hero 6
23,24,17,2025-01-31,2025-05-04,Gladiator,Mad Max: Fury Road
24,17,17,2025-02-05,2025-05-16,Dune,The Social Network
25,23,17,2025-04-07,2025-05-10,Spider-Man: No Way Home,Bohemian Rhapsody